# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: robo

before:
  hooks:
    - go mod tidy

builds:
  - id: robo
    main: ./main.go
    binary: robo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/vladimirvivien/robo/cmd.Version={{.Version}}
      - -X github.com/vladimirvivien/robo/cmd.Commit={{.FullCommit}}
      - -X github.com/vladimirvivien/robo/cmd.BuildDate={{.Date}}

archives:
  - id: robo-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  mode: replace
  replace_existing_draft: true
